export { default as AlbumPage } from './album'
export { default as AuthorPage } from './author'
export { default as ChatPage } from './chats'
export { default as DialoguePage } from './dialogue'
export { default as HistoryPage } from './history'
export { default as HomePage } from './home'
export { default as LibraryPage } from './library'
export { default as LogInPage } from './login'
export { default as LyricsEditingPage } from './lyrics-editing'
export { default as PageNotFound } from './page-not-found'
export { default as SearchPage } from './search'
export { default as SettingsPage } from './settings'
export { default as SignUpPage } from './signup'

