export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'
export const HOME_ROUTE = '/home'
export const LIBRARY_ROUTE = '/library'
export const SEARCH_ROUTE = '/search'
export const CHAT_ROUTE = '/chat'
export const NOTFOUND_ROUTE = '/no-such-page'